apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  # - secret.yaml  # copie de secret.example.yaml e preencha localmente
  - deployment-eks.yaml
  - service-loadbalancer.yaml
  # Caminho ideal (conta/dominio proprio):
  # - ingress-alb-acm.example.yaml
